incremental: bool

theme: minima

baseurl: /bhsa

org: https://github.com/ETCBC
repoBase: https://github.com/ETCBC/bhsa/blob/master
repo: https://github.com/ETCBC/bhsa
tfBase: https://github.com/Dans-labs/text-fabric/blob/master
tf: https://github.com/Dans-labs/text-fabric
tfw: https://github.com/Dans-labs/text-fabric/wiki

collections:
    features:
        output: true

defaults:
    - scope:
        path: ""
        type: features
      values:
        layout: page
    - scope:
        path: ""
        type: pages
      values:
        layout: page
    - scope:
        path: "_features/hebrew"
      values:
        lang: hebrew
        feat: true

email: 

org_url: https://github.com/ETCBC

data_repos:
  - name: bhsa
    line: Biblia Hebraica Stuttgartensia Amstelodamensis core data
  - name: parallels
    line: Parallel passages - cross references between verses
  - name: valence
    line: Verbal valence - sense descriptions for verbs depending on their context
  - name: phono
    line: Phonetic transcription of the Hebrew text
  - name: pipeline
    line: Data pipeline to make manage versions of all related data and transfer them to SHEBANQ

fleft:
    - name: Wido van Peursen
      email: w.t.van.peursen@vu.nl
      hide: false
      url: https://vu-nl.academia.edu/widovanpeursen
      institute: ETCBC
    - name: Martijn Naaijer
      email: m.naaijer@vu.nl
      hide: false
      institute: ETCBC
      url: http://etcbc.nl
    - name: Christiaan Erwich
      email: c.m.erwich@vu.nl
      hide: false
      institute: ETCBC
      url: http://etcbc.nl
    - name: Cody Kingham
      email: c.a.kingham@student.vu.nl
      hide: false
      institute: ETCBC
      url: http://etcbc.nl
    - name: Marianne Kaajan
      email: m.e.kaajan@vu.nl
      hide: false
      institute: ETCBC
      url: http://etcbc.nl

fmiddle:
    - name: text-fabric
      url: https://github.com/Dans-labs/text-fabric
      desc: Python module for processing text fabrics
    - name: wiki
      url: https://github.com/Dans-labs/text-fabric/wiki
      desc: Design, data model and API of Text-Fabric
    - name: tutorial
      url: https://github.com/Dans-labs/text-fabric/blob/master/docs/tutorial.ipynb
      desc: IPython notebook with Hebrew examples
    - name: tutorial (search)
      url: https://github.com/Dans-labs/text-fabric/blob/master/docs/searchTutorial.ipynb
      desc: IPython notebook with Greek examples
    - name: Dirk Roorda (DANS)
      desc: creator of text-fabric and the pipeline
      url: https://dans.knaw.nl/en/about/organisation-and-policy/staff/roorda

fright:
    - name: SHEBANQ website
      url: https://shebanq.ancient-data.org
      desc: View and query Hebrew dataset online
    - name: SHEBANQ on Slack
      url: https://shebanq.slack.com/signup
      desc: Signup with our Slack team
    - name: SHEBANQ admin
      url: mailto:shebanq@ancient-data.org
      desc: Mail us
    - name: SHEBANQ twitter
      url: https://twitter.com/shebanq_
      desc: follow events
