incremental: bool

theme: minima

baseurl: /bhsa

institute: http://www.etcbc.nl
org: https://github.com/ETCBC
repoBase: https://github.com/ETCBC/bhsa/blob/master
repo: https://github.com/ETCBC/bhsa
tfBase: https://github.com/Dans-labs/text-fabric/blob/master
tf: https://github.com/Dans-labs/text-fabric
tfw: https://github.com/Dans-labs/text-fabric/wiki
lf: https://github.com/Dans-labs/laf-fabric
shebanq: https://shebanq.ancient-data.org
shebanqw: https://github.com/ETCBC/shebanq/wiki
dans: https://dans.knaw.nl/nl
dbgAcademic: https://www.academic-bible.com/en/online-bibles/biblia-hebraica-stuttgartensia-bhs/read-the-bible-text/
dbgMail: mailto:zentrale@dbg.de
emdros: https://emdros.org
mql: https://emdros.org/mql.html
cc: https://creativecommons.org/licenses/by-nc/4.0/
doi3: doi.org/10.17026/dans-x8h-y2bv
doi3_url: https://doi.org/10.17026%2Fdans-x8h-y2bv 
doi4: doi.org/10.17026/dans-2z3-arxf
doi4_url: https://doi.org/10.17026/dans-2z3-arxf
doi4b: 10.17026/dans-z6y-skyh
doi4b_url: https://dx.doi.org/10.17026/dans-z6y-skyh
doi2016: doi.org/10.5281/zenodo.591507
doi2016_url: https://doi.org/10.5281/zenodo.591507
doiBhsa: doi.org/10.5281/zenodo.1007624
doiBhsa_url: https://doi.org/10.5281/zenodo.1007624
lorentz: http://www.lorentzcenter.nl/lc/web/2012/480/info.php3?wsid=480

collections:
    features:
        output: true

defaults:
    - scope:
        path: ""
        type: features
      values:
        layout: page
    - scope:
        path: ""
        type: pages
      values:
        layout: page
    - scope:
        path: "_features/hebrew"
      values:
        lang: hebrew
        feat: true

email: 

data_repos:
  - name: bhsa
    line: Biblia Hebraica Stuttgartensia Amstelodamensis core data
  - name: parallels
    line: Parallel passages - cross references between verses
  - name: valence
    line: Verbal valence - sense descriptions for verbs depending on their context
  - name: phono
    line: Phonetic transcription of the Hebrew text
  - name: pipeline
    line: Data pipeline to make manage versions of all related data and transfer them to SHEBANQ

fEtcbc:
    - name: Wido van Peursen
      url: mailto:w.t.van.peursen@vu.nl
    - name: Martijn Naaijer
      url: mailto:m.naaijer@vu.nl
    - name: Christiaan Erwich
      url: mailto:c.m.erwich@vu.nl
    - name: Cody Kingham
      url: mailto:c.a.kingham@student.vu.nl
    - name: Marianne Kaajan
      url: mailto:m.e.kaajan@vu.nl

fShebanq:
    - name: SHEBANQ website
      url: https://shebanq.ancient-data.org
      desc: View and query Hebrew dataset online
    - name: SHEBANQ wiki
      url: https://github.com/ETCBC/shebanq/wiki
      desc: Read about the whole shebanq
    - name: SHEBANQ admin
      url: mailto:shebanq@ancient-data.org
      desc: Mail us
    - name: ETCBC on Slack
      url: https://etcbc-vu.slack.com/signup
      desc: Signup with our Slack team
    - name: ETCBC twitter
      url: https://twitter.com/etcbc_vu
      desc: follow events

fTf:
    - name: text-fabric
      url: https://github.com/Dans-labs/text-fabric
      desc: Python module for processing text fabrics
    - name: wiki
      url: https://github.com/Dans-labs/text-fabric/wiki
      desc: Design, data model and API of Text-Fabric
    - name: tutorial
      url: https://github.com/Dans-labs/text-fabric/blob/master/docs/tutorial.ipynb
      desc: IPython notebook with Hebrew examples
    - name: tutorial (search)
      url: https://github.com/Dans-labs/text-fabric/blob/master/docs/searchTutorial.ipynb
      desc: IPython notebook with Greek examples

fDans:
    - name: Dirk Roorda (DANS)
      desc: developer of shebanq, text-fabric and the pipeline
      url: https://dans.knaw.nl/en/about/organisation-and-policy/staff/roorda
